import style from "./About.module.css";
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <div>
      <h1 className={style.heading}>This is about</h1>
    </div>
  );
};

export default AboutPage;
