import React from 'react';
import style from "./Contact.module.css";
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const ContactPage = () => {
    return (
        <div>
            <h1 className={style.heading}>Welcome to contact page</h1>
        </div>
    );
};

export default ContactPage;